"use client"
export interface UserItem {
  key: string;
  taxId: string;
  name: string;
  email: string;
  department: string;
  company: string;
  role: string;
  position: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  isActive: boolean;
}

export const userData: UserItem[] = [
  {
    key: "1",
    taxId: "1234567890",
    name: "Jon Snow",
    email: "jon.snow@gmail.com",
    department: "Tester Team",
    company: "INET",
    role: "Super Admin",
    position: "Tester",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "2",
    taxId: "1234567890",
    name: "Arya Stark",
    email: "arya.stark@gmail.com",
    department: "Tester Team",
    company: "INET",
    role: "Super Admin",
    position: "Tester",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "3",
    taxId: "1234567890",
    name: "Daenerys Targaryen",
    email: "daenerys.targaryen@gmail.com",
    department: "UX/UI Team",
    company: "INET",
    role: "Designer",
    position: "UX/UI Designer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "4",
    taxId: "1234567890",
    name: "Cersei Lannister",
    email: "cersei.lannister@gmail.com",
    department: "Others",
    company: "Talk to me",
    role: "Member",
    position: "Content Writer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "5",
    taxId: "1234567890",
    name: "Jaime Lannister",
    email: "jaime.lannister@gmail.com",
    department: "Developer Team",
    company: "INET",
    role: "Admin",
    position: "Frontend Developer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "6",
    taxId: "1234567890",
    name: "Tyrion Lannister",
    email: "tyrion.lannister@gmail.com",
    department: "Developer Team",
    company: "INET",
    role: "Super Admin",
    position: "Backend Developer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "7",
    taxId: "1234567890",
    name: "Brienne of Tarth",
    email: "brienne.tarth@gmail.com",
    department: "Developer Team",
    company: "INET",
    role: "Super Admin",
    position: "Frontend Developer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "8",
    taxId: "1234567890",
    name: "Davos Seaworth",
    email: "davos.seaworth@gmail.com",
    department: "Tester Team",
    company: "INET",
    role: "Member",
    position: "QA Engineer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "9",
    taxId: "1234567890",
    name: "Samwell Tarly",
    email: "samwell.tarly@gmail.com",
    department: "Developer Team",
    company: "INET",
    role: "Member",
    position: "Backend Developer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "10",
    taxId: "1234567890",
    name: "Sansa Stark",
    email: "sansa.stark@gmail.com",
    department: "Developer Team",
    company: "INET",
    role: "Member",
    position: "Backend Developer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "11",
    taxId: "1234567890",
    name: "Robb Stark",
    email: "robb.stark@gmail.com",
    department: "Developer Team",
    company: "INET",
    role: "Member",
    position: "Backend Developer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "12",
    taxId: "1234567890",
    name: "Tony Stark",
    email: "tony.stark@gmail.com",
    department: "Developer Team",
    company: "INET",
    role: "Super Admin",
    position: "Lead Developer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "13",
    taxId: "1234567890",
    name: "Bruce Wayne",
    email: "bruce.wayne@gmail.com",
    department: "Tester Team",
    company: "One Geo Survey",
    role: "Member",
    position: "QA Engineer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "14",
    taxId: "1234567890",
    name: "Clark Kent",
    email: "clark.kent@gmail.com",
    department: "UX/UI Team",
    company: "One Geo Survey",
    role: "Member",
    position: "UX/UI Designer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
  {
    key: "15",
    taxId: "1234567890",
    name: "Diana Prince",
    email: "diana.prince@gmail.com",
    department: "UX/UI Team",
    company: "INET",
    role: "Designer",
    position: "UX/UI Designer",
    status: "Active",
    createdAt: "2021-01-01",
    updatedAt: "2021-01-01",
    isActive: true,
  },
];
